---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-broken-deployment
  labels:
    app: readiness-broken-app-label
spec:
  replicas: 0
  selector:
    matchLabels:
      app: readiness-broken-app-label
  template:
    metadata:
      labels:
        app: readiness-broken-app-label
        tier: backend
    spec:
      containers:
        - name: readiness-broken-container
          image: eu.gcr.io/container-solutions-workshops//backend:3.14159
          ports:
            - containerPort: 8080
          env:
            - name: READINESS_PROBE_ENABLED
              value: "enabled"
          readinessProbe:
            httpGet:
              path: /neverready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-broken-svc
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    tier: frontend
