---
apiVersion: v1
kind: Pod
metadata:
  name: broken-pods-failed-command-pod
spec:
  containers:
    - image: busybox
      command:
        - /bin/sh
        - -c
        - "exit 1"
      name: broken-pods-failed-command-container
